### ISSUE TITLE
Question regarding GoalSelectorDebug

### ISSUE THREAD

**Issue by ghost** [SomeKitten/DebugRenderers#1]
Hey! I have a question regarding GoalSelectorDebug..

The GoalSelectors, instead of showing the goals, will show the Class names. how exactly do i disable that? 

Thanks!

**Comment by SomeKitten** [comment]
Hello! Since Minecraft's code is obfuscated when running outside of a development environment, the original names of the goals are not accessible after building the mod. If you'd like to see that information, your best bet is to open this project in an IDE like IntelliJ and running the "Minecraft Client" option!

Feel free to ask any questions if you have trouble with that!
![image](https://user-images.githubusercontent.com/30757547/190400232-ee3c82de-d5b2-4c26-82dc-614559bbbc17.png)

**Comment by ghost** [comment]
Alright thanks! I'll try it in a bit though, am quite busy atm! ill close this issue if everything went well, or ill let u know if something went wrong :D

**Comment by ghost** [comment]
Alright! I think I got it working! Thank you! sorry for the wait D:
